# Generated by Django 3.2.16 on 2023-01-18 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_Publicada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
